=== gge-tracker/i18n-beta/contributors.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="contributors">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="contributor" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name" type="xs:string" />
              <xs:element name="server" type="xs:string" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== gge-tracker/i18n-beta/contributors.xml
<?xml version="1.0" encoding="UTF-8"?>
<contributors xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="contributors.xsd">
  <contributor>
    <name>0din0</name>
    <server>IT1</server>
  </contributor>
  <contributor>
    <name>Alegz</name>
    <server>HU1</server>
  </contributor>
  <contributor>
    <name>AquaAlpaca</name>
    <server>US1</server>
  </contributor>
  <contributor>
    <name>Ausone</name>
    <server>FR1</server>
  </contributor>
  <contributor>
    <name>Aznoknis</name>
    <server>LIVE</server>
  </contributor>
  <contributor>
    <name>Black Lotus</name>
    <server>DE1</server>
  </contributor>
  <contributor>
    <name>Chancli</name>
    <server>ES1</server>
  </contributor>
  <contributor>
    <name>Danadum</name>
    <server>FR1</server>
  </contributor>
  <contributor>
    <name>Devil</name>
    <server>GB1</server>
  </contributor>
  <contributor>
    <name>Fear</name>
    <server>DE1</server>
  </contributor>
  <contributor>
    <name>Galaxy Leasco</name>
    <server>SK1</server>
  </contributor>
  <contributor>
    <name>Halt Arratay</name>
    <server>AU1</server>
  </contributor>
  <contributor>
    <name>Kevin</name>
    <server>NL1</server>
  </contributor>
  <contributor>
    <name>Orello</name>
    <server>PL1</server>
  </contributor>
  <contributor>
    <name>Oscar</name>
    <server>INT3</server>
  </contributor>
  <contributor>
    <name>Nitro0ogen</name>
    <server>SA1</server>
  </contributor>
  <contributor>
    <name>RamonRSilva</name>
    <server>HANT1</server>
  </contributor>
  <contributor>
    <name>Ritwick Rathore</name>
    <server>IN1</server>
  </contributor>
  <contributor>
    <name>Rubriq</name>
    <server>FR1</server>
  </contributor>
  <contributor>
    <name>Sadik</name>
    <server>ASIA</server>
  </contributor>
  <contributor>
    <name>Sasha1000</name>
    <server>RU1</server>
  </contributor>
  <contributor>
    <name>Satana</name>
    <server>RO1</server>
  </contributor>
  <contributor>
    <name>Sekyra</name>
    <server>CZ1</server>
  </contributor>
  <contributor>
    <name>Thomas</name>
    <server>NL1</server>
  </contributor>
  <contributor>
    <name>Thror</name>
    <server>SP3</server>
  </contributor>
  <contributor>
    <name>UysalYaramaz</name>
    <server>TR1</server>
  </contributor>
  <contributor>
    <name>Vince</name>
    <server>FR1</server>
  </contributor>
  <contributor>
    <name>wertuzi</name>
    <server>W1</server>
  </contributor>
  <contributor>
    <name>WillTheBoss</name>
    <server>RO1</server>
  </contributor>
  <contributor>
    <name>Wojts8</name>
    <server>PL1</server>
  </contributor>
  <contributor>
    <name>Xenon</name>
    <server>INT3</server>
  </contributor>
  <contributor>
    <name>ZaPor</name>
    <server>INT2</server>
  </contributor>
</contributors>
