=== gge-tracker/i18n-beta/servers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="root">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="servers">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="server" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="enabled" type="xs:string" />
										<xs:element name="featured" type="xs:string" />
										<xs:element name="gge-server-name" type="xs:string" />
										<xs:element name="name" type="xs:string" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== gge-tracker/i18n-beta/servers.xml
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="servers.xsd">
	<servers>
		<server>
			<enabled>true</enabled>
			<featured>true</featured>
			<gge-server-name>Asia</gge-server-name>
			<name>ASIA</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>false</featured>
			<gge-server-name>United Kingdom</gge-server-name>
			<name>GB1</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>false</featured>
			<gge-server-name>Egypt</gge-server-name>
			<name>EG1</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>true</featured>
			<gge-server-name>Nordic</gge-server-name>
			<name>SKN1</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>true</featured>
			<gge-server-name>Slovakia</gge-server-name>
			<name>SK1</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>true</featured>
			<gge-server-name>France</gge-server-name>
			<name>FR1</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>true</featured>
			<gge-server-name>Germany</gge-server-name>
			<name>DE1</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>true</featured>
			<gge-server-name>Romania</gge-server-name>
			<name>RO1</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>true</featured>
			<gge-server-name>Czech Republic</gge-server-name>
			<name>CZ1</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>true</featured>
			<gge-server-name>Netherlands</gge-server-name>
			<name>NL1</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>true</featured>
			<gge-server-name>World: 1</gge-server-name>
			<name>WORLD1</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>true</featured>
			<gge-server-name>World: 2</gge-server-name>
			<name>WORLD2</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>true</featured>
			<gge-server-name>International: 3</gge-server-name>
			<name>INT3</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>true</featured>
			<gge-server-name>United States</gge-server-name>
			<name>US1</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>true</featured>
			<gge-server-name>Turkey</gge-server-name>
			<name>TR1</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>false</featured>
			<gge-server-name>Portugal</gge-server-name>
			<name>PT1</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>true</featured>
			<gge-server-name>Brazil</gge-server-name>
			<name>BR1</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>true</featured>
			<gge-server-name>India</gge-server-name>
			<name>IN1</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>true</featured>
			<gge-server-name>Italy</gge-server-name>
			<name>IT1</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>false</featured>
			<gge-server-name>Poland</gge-server-name>
			<name>PL1</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>true</featured>
			<gge-server-name>Australia</gge-server-name>
			<name>AU1</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>false</featured>
			<gge-server-name>Arab League</gge-server-name>
			<name>ARAB1</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>false</featured>
			<gge-server-name>Chinese (Traditional)</gge-server-name>
			<name>HANT1</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>true</featured>
			<gge-server-name>Hungary: 1</gge-server-name>
			<name>HU1</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>false</featured>
			<gge-server-name>Hungary: 2</gge-server-name>
			<name>HU2</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>true</featured>
			<gge-server-name>Spain: 1</gge-server-name>
			<name>ES1</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>false</featured>
			<gge-server-name>Spain: 2</gge-server-name>
			<name>ES2</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>true</featured>
			<gge-server-name>Saudi Arabia</gge-server-name>
			<name>SA1</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>false</featured>
			<gge-server-name>United Arab Emirates</gge-server-name>
			<name>AE1</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>false</featured>
			<gge-server-name>International: 1</gge-server-name>
			<name>INT1</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>false</featured>
			<gge-server-name>International: 2</gge-server-name>
			<name>INT2</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>false</featured>
			<gge-server-name>Russia</gge-server-name>
			<name>RU1</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>false</featured>
			<gge-server-name>China</gge-server-name>
			<name>CN1</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>true</featured>
			<gge-server-name>Bulgaria</gge-server-name>
			<name>BG1</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>false</featured>
			<gge-server-name>Japan</gge-server-name>
			<name>JP1</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>true</featured>
			<gge-server-name>Greece</gge-server-name>
			<name>GR1</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>true</featured>
			<gge-server-name>Empire Four Kingdoms - Brazil 1</gge-server-name>
			<name>E4K_BR1</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>true</featured>
			<gge-server-name>Empire Four Kingdoms - Chinese (Traditional)</gge-server-name>
			<name>E4K_HANT1</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>true</featured>
			<gge-server-name>Empire Four Kingdoms - France 1</gge-server-name>
			<name>E4K_FR1</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>true</featured>
			<gge-server-name>Empire Four Kingdoms - Germany 1</gge-server-name>
			<name>E4K_DE1</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>true</featured>
			<gge-server-name>Empire Four Kingdoms - Germany 2</gge-server-name>
			<name>E4K_DE2</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>false</featured>
			<gge-server-name>Empire Four Kingdoms - Portugal 1</gge-server-name>
			<name>E4K_PT1</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>false</featured>
			<gge-server-name>Empire Four Kingdoms - Nordic 1</gge-server-name>
			<name>E4K_SKN1</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>false</featured>
			<gge-server-name>Empire Four Kingdoms - Netherlands 1</gge-server-name>
			<name>E4K_NL1</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>false</featured>
			<gge-server-name>Empire Four Kingdoms - United States 1</gge-server-name>
			<name>E4K_US1</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>true</featured>
			<gge-server-name>Empire Four Kingdoms - International 2</gge-server-name>
			<name>E4K_INT2</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>false</featured>
			<gge-server-name>Empire Four Kingdoms - International 4</gge-server-name>
			<name>E4K_INT4</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>true</featured>
			<gge-server-name>Empire Four Kingdoms - China 1</gge-server-name>
			<name>E4K_CN1</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>false</featured>
			<gge-server-name>Empire Four Kingdoms - United Kingdom 1</gge-server-name>
			<name>E4K_GB1</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>true</featured>
			<gge-server-name>Empire Four Kingdoms - Russia 1</gge-server-name>
			<name>E4K_RU1</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>false</featured>
			<gge-server-name>Empire Four Kingdoms - World 2</gge-server-name>
			<name>E4K_WORLD2</name>
		</server>
		<server>
			<enabled>true</enabled>
			<featured>true</featured>
			<gge-server-name>Partner server - 3</gge-server-name>
			<name>PARTNER_SP3</name>
		</server>
	</servers>
</root>
